<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <?=\Phalcon\Tag::getTitle()?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <link href="/css/style.css" rel="stylesheet">

    <script src="/js/respond.min.js"></script>
    <!--[if lt IE 9]>
    <script src="/js/html5shiv.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="/img/favicon.png">
</head>

<body>

<div class="error-page">
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="widget">
                <div class="widget-head">
                    <i class="fa fa-question-circle"></i> Ошибка
                </div>

                <div class="widget-content">
                    <div class="padd error">

                        <h1><?=$title?></h1>

                        <div class="horizontal-links">
                            <a href="/">Главная</a>
                        </div>

                    </div>
                    <div class="widget-foot">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<script src="/js/jquery.js"></script>
<script src="/js/bootstrap.min.js"></script>
</body>
</html>