<div class="row">
    <div class="col-md-12">
        <form class="form-inline" method="get" action="">
            <div class="form-group">
                <div class="input-group date datetimepicker" style="width: 300px;">
                    <?=$this->tag->textField(array('start_date', 'value'=>date('d.m.Y H:i', $start_date), 'class'=>'form-control datepickerinput'))?>
                    <span class="input-group-addon datepickerbutton"><span class="fa fa-calendar"></span></span>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group date datetimepicker" style="width: 300px;">
                    <?=$this->tag->textField(array('end_date', 'value'=>date('d.m.Y H:i', $end_date), 'class'=>'form-control datepickerinput'))?>
                    <span class="input-group-addon datepickerbutton"><span class="fa fa-calendar"></span></span>
                </div>
            </div>
            <button type="submit" class="btn btn-default">Выбрать</button>
        </form>
    </div>
</div>

<script type="text/javascript">
    var onload = function() {
        if(typeof(window.jQuery) == "function" && typeof(window.moment) == "function" && typeof(jQuery.fn.datetimepicker) == "function")
            $(document).ready(function () {
                $('.datetimepicker').datetimepicker({
                    format: 'DD.MM.YYYY HH:mm',
                    icons: {
                        time: "fa fa-clock-o",
                        date: "fa fa-calendar",
                        up: "fa fa-arrow-up",
                        down: "fa fa-arrow-down",
                        previous: 'fa fa-chevron-left',
                        next: 'fa fa-chevron-right',
                        today: 'fa fa-screenshot',
                        clear: 'fa fa-trash-o'
                    }
                });
            });
        else setTimeout(onload, 1000);
    };
    onload();
</script>

<div class="row">
    <div class="col-md-12">
        <ul class="today-datas">
            <li>
                <div><i class="fa fa-bar-chart-o" style="font-size: 30px; color: darkblue;"></i></div>
                <div class="datas-text"><?=$views?> просмотр(-ов/-а)</div>
            </li>
            <li>
                <div><i class="fa fa-share" style="font-size: 30px; color: darkred;"></i></div>
                <div class="datas-text"><?=$clicks?> клик(-ов/-а)</div>
            </li>
            <li>
                <div><span style="font-size: 30px; color: darkgreen; line-height: 30px;">CTR</span></div>
                <div class="datas-text"><?=$views == 0 ? 0 : round(($clicks / $views)*100, 2)?>%</div>
            </li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="widget">
            <div class="widget-head">
                <div class="pull-left">Статистика по дням</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content medias">
                <?php if(count($days)):?>
                    <?php
                    $days_of_week = array('Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс');
                    ?>
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Дата</th>
                            <th>Просмотров</th>
                            <th>Кликов</th>
                            <th>CTR</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($days as $day):?>
                            <?php $day_of_week = date('N', $day['date']) - 1;?>
                            <tr<?=($day_of_week == 6 || $day_of_week == 5) ? ' class="warning"' : ''?>>
                                <td><?=date('d.m.Y', $day['date'])?>, <?=$days_of_week[$day_of_week]?></td>
                                <td><?=$day['views']?></td>
                                <td><?=$day['clicks']?></td>
                                <td><?=$day['views'] == 0 ? 0 : round(($day['clicks']/$day['views'])*100, 2)?>%</td>
                            </tr>
                        <?php endforeach?>

                        </tbody>
                    </table>
                <?php else:?>
                    <p class="none">Статистика за выбранный период отсутствует.</p>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>