<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <?=\Phalcon\Tag::getTitle()?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <link href="/css/style.css" rel="stylesheet">

    <script src="/js/respond.min.js"></script>
    <!--[if lt IE 9]>
    <script src="/js/html5shiv.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="/img/favicon.png">
</head>

<body>

<div class="admin-form">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="widget worange">
                    <div class="widget-head">
                        <i class="fa fa-lock"></i> Вход
                    </div>
                    <div class="widget-content">
                        <div class="padd">
                            <?php $this->flashSession->output();?>
                            <form class="form-horizontal" method="POST" action="">
                                <div class="form-group">
                                    <label class="control-label col-lg-3" for="inputEmail">Email</label>
                                    <div class="col-lg-9">
                                        <input type="text" class="form-control" id="inputEmail" name="username" placeholder="Email">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-3" for="inputPassword">Пароль</label>
                                    <div class="col-lg-9">
                                        <input type="password" class="form-control" id="inputPassword" name="password" placeholder="Пароль">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-lg-9 col-lg-offset-3">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="remember"> Запомнить меня
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-9 col-lg-offset-3">
                                    <button type="submit" class="btn btn-info btn-sm">Войти</button>
                                    <button type="reset" class="btn btn-default btn-sm">Очистить</button>
                                </div>
                                <br />
                            </form>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<script src="/js/jquery.js"></script>
<script src="/js/bootstrap.min.js"></script>
</body>
</html>