<div class="row">
    <div class="col-md-12">
        <a class="btn btn-success btn-lg btn-block" href="<?=$this->url->get(array('for'=>'action', 'controller'=>'zones', 'action'=>'add'))?>"><i class="fa fa-plus"></i> Создать новую зону</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="widget">
            <div class="widget-head">
                <div class="pull-left">Список</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content medias">
                <?php if(count($zones)):?>
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Код для сайта</th>
                        <th>Ссылка для запроса с мобильных приложений</th>
                        <th>Действия</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($zones as $zone):?>
                    <tr>
                        <td><?=$zone->id?></td>
                        <td><a href="<?=$this->url->get(array('for'=>'full', 'controller'=>'zones', 'action'=>'edit', 'id'=>$zone->id))?>"><?=$zone->name?></a></td>
                        <td>
                            <input class="form-control self_selected" type="text" value="<?=htmlspecialchars("<div id=\"banners_zone_{$zone->id}\"></div><script type=\"text/javascript\">new Banner(\"banners_zone_{$zone->id}\", {$zone->id});</script>");?>">
                        </td>
                        <td>
                            <input class="form-control self_selected" type="text" value="<?=$zone->get_mobile_link()?>">
                        </td>
                        <td>
                            <a class="btn btn-xs btn-default" href="<?=$this->url->get(array('for'=>'full', 'controller'=>'zones', 'action'=>'edit', 'id'=>$zone->id))?>"><i class="fa fa-pencil"></i></a>
                            <a class="btn btn-xs btn-danger" href="<?=$this->url->get(array('for'=>'full', 'controller'=>'zones', 'action'=>'delete', 'id'=>$zone->id))?>"><i class="fa fa-times"></i></a>
                        </td>
                    </tr>
                    <?php endforeach?>

                    </tbody>
                </table>
                <?php else:?>
                <p class="none">Нет зон. <a href="<?=$this->url->get(array('for'=>'action', 'controller'=>'zones', 'action'=>'add'))?>">Создать?</a></p>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>