<div class="row">
    <div class="col-md-6">
        <div class="widget">
            <div class="widget-head">
                <div class="pull-left">Список активных баннеров</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <?php if(count($active_banners)):?>
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Кликов</th>
                            <th>Показов</th>
                            <th>CTR</th>
                            <th>Предел по показам</th>
                            <th>Дата начала показа</th>
                            <th>Дата конца показа</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($active_banners as $banner):?>
                            <tr>
                                <td><a href="<?=$this->url->get(array('for'=>'full', 'controller'=>'banners', 'action'=>'statistic', 'id'=>$banner->id))?>"><?=$banner->name?></a></td>
                                <td><?php $cliсks = $banner->countViews(array('clicked = 1')); echo $cliсks;?></td>
                                <td><?php $views = $banner->countViews(); echo $views;?></td>
                                <td><?=round(($cliсks / $views) * 100, 2)?>%</td>
                                <td><?=!empty($banner->max_impressions) ? $banner->max_impressions : '&infin;'?></td>
                                <td><?=!empty($banner->start_date) ? $banner->getStartDate() : '&infin;'?></td>
                                <td><?=!empty($banner->end_date) ? $banner->getEndDate() : '&infin;'?></td>
                            </tr>
                        <?php endforeach?>

                        </tbody>
                    </table>
                <?php else:?>
                <p class="none">Нет баннеров.</p>
                <?php endif;?>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="widget">
            <div class="widget-head">
                <div class="pull-left">Список выполненных баннеров</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <?php if(count($finished_banners)):?>
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Кликов</th>
                            <th>Показов</th>
                            <th>CTR</th>
                            <th>Предел по показам</th>
                            <th>Дата начала показа</th>
                            <th>Дата конца показа</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($finished_banners as $banner):?>
                            <tr>
                                <td><a href="<?=$this->url->get(array('for'=>'full', 'controller'=>'banners', 'action'=>'statistic', 'id'=>$banner->id))?>"><?=$banner->name?></a></td>
                                <td><?php $cliсks = $banner->countViews(array('clicked = 1')); echo $cliсks;?></td>
                                <td><?php $views = $banner->countViews(); echo $views;?></td>
                                <td><?=round(($cliсks / $views) * 100, 2)?>%</td>
                                <td><?=!empty($banner->max_impressions) ? $banner->max_impressions : '&infin;'?></td>
                                <td><?=!empty($banner->start_date) ? $banner->getStartDate() : '&infin;'?></td>
                                <td><?=!empty($banner->end_date) ? $banner->getEndDate() : '&infin;'?></td>
                            </tr>
                        <?php endforeach?>

                        </tbody>
                    </table>
                <?php else:?>
                    <p class="none">Нет баннеров.</p>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>